package frc.robot.subsystems;

import com.revrobotics.AbsoluteEncoder;
import com.revrobotics.CANSparkMax;
import com.revrobotics.RelativeEncoder;
import com.revrobotics.SparkMaxAbsoluteEncoder;
import com.revrobotics.SparkMaxLimitSwitch;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;



public class Arm extends SubsystemBase{

   public static final int deviceID =
   
   
   
   
   
   
   
   
    @Override 
    public void periodic() {
    }   
}

